In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("sorting_ranking_practice.csv")
df.head()

   OriginalIndex EmployeeName  Age       City  Salary  Score   Department
0             12  Riya Sharma   28      Delhi   52000     88    Analytics
1              3  Kabir Singh   24       Pune   41000     76  Engineering
2             15  Meera Patel   28     Mumbai   61000     92    Analytics
3              1  Arjun Verma   31  Bengaluru   72000     88  Engineering
4             10    Sara Khan   24      Delhi   39000     76      Support

In [4]:
df.sort_values("Age")

    OriginalIndex  EmployeeName  Age       City  Salary  Score   Department
1               3   Kabir Singh   24       Pune   41000     76  Engineering
4              10     Sara Khan   24      Delhi   39000     76      Support
8               9      Neha Rao   24  Bengaluru   43000     81  Engineering
13             11    Ishaan Roy   26     Mumbai   46000     76      Support
14              5     Tara Nair   26       Pune   44000     81  Engineering
10             13    Anaya Bose   27       Pune   50000     81    Analytics
6              14    Isha Gupta   27     Mumbai   48000     88      Support
0              12   Riya Sharma   28      Delhi   52000     88    Analytics
2              15   Meera Patel   28     Mumbai   61000     92    Analytics
12              2      Zoya Ali   29  Bengaluru   59000     92    Analytics
11              7   Rohan Mehta   29      Delhi   57000     88      Support
3               1   Arjun Verma   31  Bengaluru   72000     88  Engineering
7               0    Aman Joshi   31      Delhi   68000     92    Analytics
15              8   Karan Sethi   32      Delhi   74000     95    Analytics
5               6  Dev Malhotra   35       Pune   85000     95  Engineering
9               4    Vikram Das   35     Mumbai   91000     95  Engineering

In [5]:
df.sort_values("Age", ascending = False)

    OriginalIndex  EmployeeName  Age       City  Salary  Score   Department
5               6  Dev Malhotra   35       Pune   85000     95  Engineering
9               4    Vikram Das   35     Mumbai   91000     95  Engineering
15              8   Karan Sethi   32      Delhi   74000     95    Analytics
3               1   Arjun Verma   31  Bengaluru   72000     88  Engineering
7               0    Aman Joshi   31      Delhi   68000     92    Analytics
12              2      Zoya Ali   29  Bengaluru   59000     92    Analytics
11              7   Rohan Mehta   29      Delhi   57000     88      Support
0              12   Riya Sharma   28      Delhi   52000     88    Analytics
2              15   Meera Patel   28     Mumbai   61000     92    Analytics
10             13    Anaya Bose   27       Pune   50000     81    Analytics
6              14    Isha Gupta   27     Mumbai   48000     88      Support
13             11    Ishaan Roy   26     Mumbai   46000     76      Support
14              5     Tara Nair   26       Pune   44000     81  Engineering
1               3   Kabir Singh   24       Pune   41000     76  Engineering
4              10     Sara Khan   24      Delhi   39000     76      Support
8               9      Neha Rao   24  Bengaluru   43000     81  Engineering

In [6]:
df.sort_values(["Age", "Salary"])

    OriginalIndex  EmployeeName  Age       City  Salary  Score   Department
4              10     Sara Khan   24      Delhi   39000     76      Support
1               3   Kabir Singh   24       Pune   41000     76  Engineering
8               9      Neha Rao   24  Bengaluru   43000     81  Engineering
14              5     Tara Nair   26       Pune   44000     81  Engineering
13             11    Ishaan Roy   26     Mumbai   46000     76      Support
6              14    Isha Gupta   27     Mumbai   48000     88      Support
10             13    Anaya Bose   27       Pune   50000     81    Analytics
0              12   Riya Sharma   28      Delhi   52000     88    Analytics
2              15   Meera Patel   28     Mumbai   61000     92    Analytics
11              7   Rohan Mehta   29      Delhi   57000     88      Support
12              2      Zoya Ali   29  Bengaluru   59000     92    Analytics
7               0    Aman Joshi   31      Delhi   68000     92    Analytics
3               1   Arjun Verma   31  Bengaluru   72000     88  Engineering
15              8   Karan Sethi   32      Delhi   74000     95    Analytics
5               6  Dev Malhotra   35       Pune   85000     95  Engineering
9               4    Vikram Das   35     Mumbai   91000     95  Engineering

In [7]:
df.sort_index()

    OriginalIndex  EmployeeName  Age       City  Salary  Score   Department
0              12   Riya Sharma   28      Delhi   52000     88    Analytics
1               3   Kabir Singh   24       Pune   41000     76  Engineering
2              15   Meera Patel   28     Mumbai   61000     92    Analytics
3               1   Arjun Verma   31  Bengaluru   72000     88  Engineering
4              10     Sara Khan   24      Delhi   39000     76      Support
5               6  Dev Malhotra   35       Pune   85000     95  Engineering
6              14    Isha Gupta   27     Mumbai   48000     88      Support
7               0    Aman Joshi   31      Delhi   68000     92    Analytics
8               9      Neha Rao   24  Bengaluru   43000     81  Engineering
9               4    Vikram Das   35     Mumbai   91000     95  Engineering
10             13    Anaya Bose   27       Pune   50000     81    Analytics
11              7   Rohan Mehta   29      Delhi   57000     88      Support
12              2      Zoya Ali   29  Bengaluru   59000     92    Analytics
13             11    Ishaan Roy   26     Mumbai   46000     76      Support
14              5     Tara Nair   26       Pune   44000     81  Engineering
15              8   Karan Sethi   32      Delhi   74000     95    Analytics

In [8]:
df.reset_index(drop = True, inplace = True)

In [9]:
df

    OriginalIndex  EmployeeName  Age       City  Salary  Score   Department
0              12   Riya Sharma   28      Delhi   52000     88    Analytics
1               3   Kabir Singh   24       Pune   41000     76  Engineering
2              15   Meera Patel   28     Mumbai   61000     92    Analytics
3               1   Arjun Verma   31  Bengaluru   72000     88  Engineering
4              10     Sara Khan   24      Delhi   39000     76      Support
5               6  Dev Malhotra   35       Pune   85000     95  Engineering
6              14    Isha Gupta   27     Mumbai   48000     88      Support
7               0    Aman Joshi   31      Delhi   68000     92    Analytics
8               9      Neha Rao   24  Bengaluru   43000     81  Engineering
9               4    Vikram Das   35     Mumbai   91000     95  Engineering
10             13    Anaya Bose   27       Pune   50000     81    Analytics
11              7   Rohan Mehta   29      Delhi   57000     88      Support
12              2      Zoya Ali   29  Bengaluru   59000     92    Analytics
13             11    Ishaan Roy   26     Mumbai   46000     76      Support
14              5     Tara Nair   26       Pune   44000     81  Engineering
15              8   Karan Sethi   32      Delhi   74000     95    Analytics

In [11]:
df["Rank"] = df["Score"].rank()

In [12]:
df

,OriginalIndex,EmployeeName,Age,City,Salary,Score,Department,Rank
0,12,Riya Sharma,28,Delhi,52000,88,Analytics,8.5
1,3,Kabir Singh,24,Pune,41000,76,Engineering,2.0
2,15,Meera Patel,28,Mumbai,61000,92,Analytics,12.0
3,1,Arjun Verma,31,Bengaluru,72000,88,Engineering,8.5
4,10,Sara Khan,24,Delhi,39000,76,Support,2.0
5,6,Dev Malhotra,35,Pune,85000,95,Engineering,15.0
6,14,Isha Gupta,27,Mumbai,48000,88,Support,8.5
7,0,Aman Joshi,31,Delhi,68000,92,Analytics,12.0
8,9,Neha Rao,24,Bengaluru,43000,81,Engineering,5.0
9,4,Vikram Das,35,Mumbai,91000,95,Engineering,15.0
10,13,Anaya Bose,27,Pune,50000,81,Analytics,5.0
11,7,Rohan Mehta,29,Delhi,57000,88,Support,8.5
12,2,Zoya Ali,29,Bengaluru,59000,92,Analytics,12.0
13,11,Ishaan Roy,26,Mumbai,46000,76,Support,2.0
14,5,Tara Nair,26,Pune,44000,81,Engineering,5.0
15,8,Karan Sethi,32,Delhi,74000,95,Analytics,15.0

In [16]:
df["Rank"] = df["Score"].rank(method ='dense')
df

,OriginalIndex,EmployeeName,Age,City,Salary,Score,Department,Rank
0,12,Riya Sharma,28,Delhi,52000,88,Analytics,3.0
1,3,Kabir Singh,24,Pune,41000,76,Engineering,1.0
2,15,Meera Patel,28,Mumbai,61000,92,Analytics,4.0
3,1,Arjun Verma,31,Bengaluru,72000,88,Engineering,3.0
4,10,Sara Khan,24,Delhi,39000,76,Support,1.0
5,6,Dev Malhotra,35,Pune,85000,95,Engineering,5.0
6,14,Isha Gupta,27,Mumbai,48000,88,Support,3.0
7,0,Aman Joshi,31,Delhi,68000,92,Analytics,4.0
8,9,Neha Rao,24,Bengaluru,43000,81,Engineering,2.0
9,4,Vikram Das,35,Mumbai,91000,95,Engineering,5.0
10,13,Anaya Bose,27,Pune,50000,81,Analytics,2.0
11,7,Rohan Mehta,29,Delhi,57000,88,Support,3.0
12,2,Zoya Ali,29,Bengaluru,59000,92,Analytics,4.0
13,11,Ishaan Roy,26,Mumbai,46000,76,Support,1.0
14,5,Tara Nair,26,Pune,44000,81,Engineering,2.0
15,8,Karan Sethi,32,Delhi,74000,95,Analytics,5.0

In [17]:
df.sort_values("Rank")

,OriginalIndex,EmployeeName,Age,City,Salary,Score,Department,Rank
1,3,Kabir Singh,24,Pune,41000,76,Engineering,1.0
4,10,Sara Khan,24,Delhi,39000,76,Support,1.0
13,11,Ishaan Roy,26,Mumbai,46000,76,Support,1.0
8,9,Neha Rao,24,Bengaluru,43000,81,Engineering,2.0
10,13,Anaya Bose,27,Pune,50000,81,Analytics,2.0
14,5,Tara Nair,26,Pune,44000,81,Engineering,2.0
3,1,Arjun Verma,31,Bengaluru,72000,88,Engineering,3.0
0,12,Riya Sharma,28,Delhi,52000,88,Analytics,3.0
11,7,Rohan Mehta,29,Delhi,57000,88,Support,3.0
6,14,Isha Gupta,27,Mumbai,48000,88,Support,3.0
2,15,Meera Patel,28,Mumbai,61000,92,Analytics,4.0
7,0,Aman Joshi,31,Delhi,68000,92,Analytics,4.0
12,2,Zoya Ali,29,Bengaluru,59000,92,Analytics,4.0
5,6,Dev Malhotra,35,Pune,85000,95,Engineering,5.0
9,4,Vikram Das,35,Mumbai,91000,95,Engineering,5.0
15,8,Karan Sethi,32,Delhi,74000,95,Analytics,5.0

In [21]:
df2 = df.rename(columns={"EmployeeName":"Name", "Score":"PerformanceScore"}).copy()

In [22]:
df2

,OriginalIndex,Name,Age,City,Salary,PerformanceScore,Department,Rank
0,12,Riya Sharma,28,Delhi,52000,88,Analytics,3.0
1,3,Kabir Singh,24,Pune,41000,76,Engineering,1.0
2,15,Meera Patel,28,Mumbai,61000,92,Analytics,4.0
3,1,Arjun Verma,31,Bengaluru,72000,88,Engineering,3.0
4,10,Sara Khan,24,Delhi,39000,76,Support,1.0
5,6,Dev Malhotra,35,Pune,85000,95,Engineering,5.0
6,14,Isha Gupta,27,Mumbai,48000,88,Support,3.0
7,0,Aman Joshi,31,Delhi,68000,92,Analytics,4.0
8,9,Neha Rao,24,Bengaluru,43000,81,Engineering,2.0
9,4,Vikram Das,35,Mumbai,91000,95,Engineering,5.0
10,13,Anaya Bose,27,Pune,50000,81,Analytics,2.0
11,7,Rohan Mehta,29,Delhi,57000,88,Support,3.0
12,2,Zoya Ali,29,Bengaluru,59000,92,Analytics,4.0
13,11,Ishaan Roy,26,Mumbai,46000,76,Support,1.0
14,5,Tara Nair,26,Pune,44000,81,Engineering,2.0
15,8,Karan Sethi,32,Delhi,74000,95,Analytics,5.0

In [24]:
df2 = df2.rename(index={0: "row1", 1: "row2"})

In [27]:
df2.head()

,OriginalIndex,Name,Age,City,Salary,PerformanceScore,Department,Rank
row1,12,Riya Sharma,28,Delhi,52000,88,Analytics,3.0
row2,3,Kabir Singh,24,Pune,41000,76,Engineering,1.0
2,15,Meera Patel,28,Mumbai,61000,92,Analytics,4.0
3,1,Arjun Verma,31,Bengaluru,72000,88,Engineering,3.0
4,10,Sara Khan,24,Delhi,39000,76,Support,1.0

In [28]:
cols = ["Name"] + [col for col in df2.columns if col != "Name"]
df2 = df2[cols]

In [29]:
df2

,Name,OriginalIndex,Age,City,Salary,PerformanceScore,Department,Rank
row1,Riya Sharma,12,28,Delhi,52000,88,Analytics,3.0
row2,Kabir Singh,3,24,Pune,41000,76,Engineering,1.0
2,Meera Patel,15,28,Mumbai,61000,92,Analytics,4.0
3,Arjun Verma,1,31,Bengaluru,72000,88,Engineering,3.0
4,Sara Khan,10,24,Delhi,39000,76,Support,1.0
5,Dev Malhotra,6,35,Pune,85000,95,Engineering,5.0
6,Isha Gupta,14,27,Mumbai,48000,88,Support,3.0
7,Aman Joshi,0,31,Delhi,68000,92,Analytics,4.0
8,Neha Rao,9,24,Bengaluru,43000,81,Engineering,2.0
9,Vikram Das,4,35,Mumbai,91000,95,Engineering,5.0
10,Anaya Bose,13,27,Pune,50000,81,Analytics,2.0
11,Rohan Mehta,7,29,Delhi,57000,88,Support,3.0
12,Zoya Ali,2,29,Bengaluru,59000,92,Analytics,4.0
13,Ishaan Roy,11,26,Mumbai,46000,76,Support,1.0
14,Tara Nair,5,26,Pune,44000,81,Engineering,2.0
15,Karan Sethi,8,32,Delhi,74000,95,Analytics,5.0