In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 21, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [3]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   21 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [4]:
df.groupby("Department")["Salary"].mean()

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [5]:
df.groupby(["Team", "Gender"])["Salary"].min()

Team  Gender
A     F         90
      M         85
B     F         85
      M         78
C     F         88
      M         92
D     F         80
      M         75
Name: Salary, dtype: int64

In [6]:
df.groupby("Age")["Salary"].agg([
    "mean",
    "sum",
    "max"
])

     mean  sum  max
Age
21   80.0  160   85
23   85.0   85   85
25   90.0   90   90
26   88.0   88   88
27   80.0   80   80
28   92.0   92   92
30   78.0   78   78

In [8]:
df.groupby("Age")["Salary"].agg(
    avgSalary="mean",
    totalSalary="sum",
    MaxCurrSalary="max"
)

     avgSalary  totalSalary  MaxCurrSalary
Age
21        80.0          160             85
23        85.0           85             85
25        90.0           90             90
26        88.0           88             88
27        80.0           80             80
28        92.0           92             92
30        78.0           78             78

In [10]:
df.groupby("Team").agg({
    "Salary": "mean",
    "Age": "max"
})

      Salary  Age
Team
A       87.5   25
B       81.5   30
C       90.0   28
D       77.5   27

In [11]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   21 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [12]:
df["Team Avg"] = df.groupby("Team")["Salary"].transform("mean") #take Teams then calc avg of salaries for teams and then new row

In [13]:
df

  Department Team Gender  Salary  Age   JoinDate  Team Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    B      F      85   21 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0
6      Sales    D      M      75   21 2021-07-15      77.5
7      Sales    D      F      80   27 2021-08-01      77.5

In [14]:
df2 = df.groupby("Department").filter(lambda x: x["Salary"].mean() > 85)