In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("filter.csv")
df.head()

,Actor,Film,Year,Revenue (Millions $),IMDb Rating
0,Dwayne Johnson,Jumanji: The Next Level,2019,$800,6.7
1,Will Smith,Men in Black 3,2012,$624,6.8
2,Chris Pratt,Jurassic World,2015,"$1,671",6.9
3,Angelina Jolie,Maleficent,2014,$758,6.9
4,Will Smith,Aladdin,2019,"$1,050",6.9

In [3]:
df[["Film", "Revenue (Millions $)"]].head()

                      Film Revenue (Millions $)
0  Jumanji: The Next Level                 $800
1           Men in Black 3                 $624
2           Jurassic World               $1,671
3               Maleficent                 $758
4                  Aladdin               $1,050

In [4]:
df.loc[0]

Actor                            Dwayne Johnson
Film                    Jumanji: The Next Level
Year                                       2019
Revenue (Millions $)                       $800
IMDb Rating                                 6.7
Name: 0, dtype: object

In [5]:
df.iloc[7]

Actor                   Robert Downey Jr.
Film                           Iron Man 3
Year                                 2013
Revenue (Millions $)               $1,214
IMDb Rating                           7.1
Name: 7, dtype: object

In [6]:
df.loc[df["IMDb Rating"]>7.4].head()

,Actor,Film,Year,Revenue (Millions $),IMDb Rating
5,Brad Pitt,Once Upon a Time in Hollywood,2019,$374,7.6
6,Leonardo DiCaprio,The Titanic,1997,"$2,257",7.9
12,Leonardo DiCaprio,Inception,2010,$836,8.8
13,Tom Cruise,Top Gun: Maverick,2022,"$1,493",8.3
15,Jennifer Lawrence,Catching Fire,2013,$865,7.5

In [7]:
df.iloc[6,3]

'$2,257'

In [8]:
df.head()

,Actor,Film,Year,Revenue (Millions $),IMDb Rating
0,Dwayne Johnson,Jumanji: The Next Level,2019,$800,6.7
1,Will Smith,Men in Black 3,2012,$624,6.8
2,Chris Pratt,Jurassic World,2015,"$1,671",6.9
3,Angelina Jolie,Maleficent,2014,$758,6.9
4,Will Smith,Aladdin,2019,"$1,050",6.9

In [9]:
df['Revenue (Millions $)'] = pd.to_numeric(df['Revenue (Millions $)'].str.replace('$','',regex = False).str.replace(',','',regex=False))
df

,Actor,Film,Year,Revenue (Millions $),IMDb Rating
0,Dwayne Johnson,Jumanji: The Next Level,2019,800,6.7
1,Will Smith,Men in Black 3,2012,624,6.8
2,Chris Pratt,Jurassic World,2015,1671,6.9
3,Angelina Jolie,Maleficent,2014,758,6.9
4,Will Smith,Aladdin,2019,1050,6.9
5,Brad Pitt,Once Upon a Time in Hollywood,2019,374,7.6
6,Leonardo DiCaprio,The Titanic,1997,2257,7.9
7,Robert Downey Jr.,Iron Man 3,2013,1214,7.1
8,Scarlett Johansson,Lucy,2014,463,6.4
9,Margot Robbie,Barbie,2023,1445,6.9
10,Jennifer Lawrence,The Hunger Games,2012,694,7.2
11,Brad Pitt,World War Z,2013,540,7.0
12,Leonardo DiCaprio,Inception,2010,836,8.8
13,Tom Cruise,Top Gun: Maverick,2022,1493,8.3
14,Meryl Streep,Mamma Mia!,2008,611,6.5
15,Jennifer Lawrence,Catching Fire,2013,865,7.5
16,Chris Pratt,Guardians of the Galaxy,2014,773,8.0
17,Meryl Streep,The Devil Wears Prada,2006,326,6.9
18,Tom Hanks,Forrest Gump,1994,678,8.8
19,Dwayne Johnson,Fast & Furious Present: Hobbs & Shaw,2019,760,6.5
20,Tom Hanks,Toy Story 3,2010,1067,8.3
21,Tom Cruise,Mission: Impossible - Fallout,2018,791,7.7

In [10]:
df.head()

,Actor,Film,Year,Revenue (Millions $),IMDb Rating
0,Dwayne Johnson,Jumanji: The Next Level,2019,800,6.7
1,Will Smith,Men in Black 3,2012,624,6.8
2,Chris Pratt,Jurassic World,2015,1671,6.9
3,Angelina Jolie,Maleficent,2014,758,6.9
4,Will Smith,Aladdin,2019,1050,6.9

In [15]:
df[(df["Revenue (Millions $)"] <= 800) & (df["Year"]==2019)]

,Actor,Film,Year,Revenue (Millions $),IMDb Rating
0,Dwayne Johnson,Jumanji: The Next Level,2019,800,6.7
5,Brad Pitt,Once Upon a Time in Hollywood,2019,374,7.6
19,Dwayne Johnson,Fast & Furious Present: Hobbs & Shaw,2019,760,6.5

In [16]:
df.head()

,Actor,Film,Year,Revenue (Millions $),IMDb Rating
0,Dwayne Johnson,Jumanji: The Next Level,2019,800,6.7
1,Will Smith,Men in Black 3,2012,624,6.8
2,Chris Pratt,Jurassic World,2015,1671,6.9
3,Angelina Jolie,Maleficent,2014,758,6.9
4,Will Smith,Aladdin,2019,1050,6.9

In [17]:
col = "Actor"
df.query(f"{col}.str.len() > 12") #use .str accessor

,Actor,Film,Year,Revenue (Millions $),IMDb Rating
0,Dwayne Johnson,Jumanji: The Next Level,2019,800,6.7
3,Angelina Jolie,Maleficent,2014,758,6.9
6,Leonardo DiCaprio,The Titanic,1997,2257,7.9
7,Robert Downey Jr.,Iron Man 3,2013,1214,7.1
8,Scarlett Johansson,Lucy,2014,463,6.4
9,Margot Robbie,Barbie,2023,1445,6.9
10,Jennifer Lawrence,The Hunger Games,2012,694,7.2
12,Leonardo DiCaprio,Inception,2010,836,8.8
15,Jennifer Lawrence,Catching Fire,2013,865,7.5
19,Dwayne Johnson,Fast & Furious Present: Hobbs & Shaw,2019,760,6.5

In [20]:
df.query("Film == 'Lucy'")

                Actor  Film  Year  Revenue (Millions $)  IMDb Rating
8  Scarlett Johansson  Lucy  2014                   463          6.4

In [21]:
df.head()

,Actor,Film,Year,Revenue (Millions $),IMDb Rating
0,Dwayne Johnson,Jumanji: The Next Level,2019,800,6.7
1,Will Smith,Men in Black 3,2012,624,6.8
2,Chris Pratt,Jurassic World,2015,1671,6.9
3,Angelina Jolie,Maleficent,2014,758,6.9
4,Will Smith,Aladdin,2019,1050,6.9

In [22]:
df.query("`Revenue (Millions $)` >800") #in .query for col name with space or char use (``) backticks

,Actor,Film,Year,Revenue (Millions $),IMDb Rating
2,Chris Pratt,Jurassic World,2015,1671,6.9
4,Will Smith,Aladdin,2019,1050,6.9
6,Leonardo DiCaprio,The Titanic,1997,2257,7.9
7,Robert Downey Jr.,Iron Man 3,2013,1214,7.1
9,Margot Robbie,Barbie,2023,1445,6.9
12,Leonardo DiCaprio,Inception,2010,836,8.8
13,Tom Cruise,Top Gun: Maverick,2022,1493,8.3
15,Jennifer Lawrence,Catching Fire,2013,865,7.5
20,Tom Hanks,Toy Story 3,2010,1067,8.3

In [23]:
rating = 8.4
df.query("`IMDb Rating` > @rating") #without f-String can use '@' also for var name stored

                Actor          Film  Year  Revenue (Millions $)  IMDb Rating
12  Leonardo DiCaprio     Inception  2010                   836          8.8
18          Tom Hanks  Forrest Gump  1994                   678          8.8