In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("pandas_data_cleaning_practice.csv")

In [4]:
df.head()

,Name,Age,Gender,City,Email,JoinDate,Category,Salary
0,Aayush,23.0,M,Del,aayush@example.com,2024-01-15,Analyst,28000.0
1,riya,24.0,F,Delhi,riya.sharma@example.com,01/20/2024,Analyst,32000.0
2,Karan,NaN,M,Mum,karan@example.com,2024-02-03,Developer,45000.0
3,Neha,22.0,F,Mumbai,NaN,02/10/2024,Developer,42000.0
4,Aman,27.0,M,delhi,aman@example.com,2024-03-01,Analyst,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      20 non-null     object
 1   Age       18 non-null     float64
 2   Gender    19 non-null     object
 3   City      20 non-null     object
 4   Email     19 non-null     object
 5   JoinDate  19 non-null     object
 6   Category  20 non-null     object
 7   Salary    19 non-null     float64
dtypes: float64(2), object(6)
memory usage: 1.4+ KB

In [8]:
df.dtypes

Name         object
Age         float64
Gender       object
City         object
Email        object
JoinDate     object
Category     object
Salary      float64
dtype: object

In [10]:
df.isnull().sum()

Name        0
Age         2
Gender      1
City        0
Email       1
JoinDate    1
Category    0
Salary      1
dtype: int64

In [13]:
df2 = df.dropna().copy()

In [15]:
df2.isnull().sum()

Name        0
Age         0
Gender      0
City        0
Email       0
JoinDate    0
Category    0
Salary      0
dtype: int64

In [16]:
df2.head()

,Name,Age,Gender,City,Email,JoinDate,Category,Salary
0,Aayush,23.0,M,Del,aayush@example.com,2024-01-15,Analyst,28000.0
1,riya,24.0,F,Delhi,riya.sharma@example.com,01/20/2024,Analyst,32000.0
5,Priya,24.0,F,Delhi,riya.sharma@example.com,2024-01-20,Analyst,32000.0
6,Vikram,31.0,M,Bengaluru,vikram@example.com,2024-03-15,Manager,60000.0
8,Rohan,29.0,M,Delhi NCR,rohan@example.com,2024-04-02,Developer,50000.0

In [25]:
df.head()

,Name,Age,Gender,City,Email,JoinDate,Category,Salary
0,Aayush,23.0,M,Del,aayush@example.com,2024-01-15,Analyst,28000.0
1,riya,24.0,F,Delhi,riya.sharma@example.com,01/20/2024,Analyst,32000.0
2,Karan,NaN,M,Mum,karan@example.com,2024-02-03,Developer,45000.0
3,Neha,22.0,F,Mumbai,NaN,02/10/2024,Developer,42000.0
4,Aman,27.0,M,delhi,aman@example.com,2024-03-01,Analyst,NaN

In [24]:
df["Age"].fillna(df["Age"].mean())

0     23.000000
1     24.000000
2     24.777778
3     22.000000
4     27.000000
5     24.000000
6     31.000000
7     17.000000
8     29.000000
9     26.000000
10    35.000000
11    21.000000
12    19.000000
13    24.777778
14    16.000000
15    28.000000
16    25.000000
17    30.000000
18    26.000000
19    23.000000
Name: Age, dtype: float64

In [26]:
df["Salary"].fillna(df["Salary"].median())

0     28000.0
1     32000.0
2     45000.0
3     42000.0
4     39000.0
5     32000.0
6     60000.0
7     15000.0
8     50000.0
9     36000.0
10    72000.0
11    18000.0
12    39000.0
13    45000.0
14    14000.0
15    41000.0
16    47000.0
17    68000.0
18    36000.0
19    38000.0
Name: Salary, dtype: float64

In [28]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18     True
19    False
dtype: bool

In [29]:
df.drop_duplicates()

,Name,Age,Gender,City,Email,JoinDate,Category,Salary
0,Aayush,23.0,M,Del,aayush@example.com,2024-01-15,Analyst,28000.0
1,riya,24.0,F,Delhi,riya.sharma@example.com,01/20/2024,Analyst,32000.0
2,Karan,NaN,M,Mum,karan@example.com,2024-02-03,Developer,45000.0
3,Neha,22.0,F,Mumbai,NaN,02/10/2024,Developer,42000.0
4,Aman,27.0,M,delhi,aman@example.com,2024-03-01,Analyst,NaN
5,Priya,24.0,F,Delhi,riya.sharma@example.com,2024-01-20,Analyst,32000.0
6,Vikram,31.0,M,Bengaluru,vikram@example.com,2024-03-15,Manager,60000.0
7,Sara,17.0,F,Mum,sara@example.com,NaN,Intern,15000.0
8,Rohan,29.0,M,Delhi NCR,rohan@example.com,2024-04-02,Developer,50000.0
9,Meera,26.0,F,Pune,meera@example.com,04/12/2024,Analyst,36000.0
10,Dev,35.0,M,Bengaluru,dev@example.com,2024-05-01,Manager,72000.0
11,Isha,21.0,F,Del,isha@example.com,2024-05-14,Intern,18000.0
12,Arjun,19.0,M,Pune,arjun@example.com,2024-06-01,Developer,39000.0
14,Tara,16.0,F,Delhi,tara@example.com,2024-06-18,Intern,14000.0
15,Kabir,28.0,NaN,Chennai,kabir@example.com,2024-07-04,Analyst,41000.0
16,Anaya,25.0,F,Pune,anaya@example.com,2024-07-19,Developer,47000.0
17,Ishaan,30.0,M,Bengaluru,ishaan@example.com,2024-08-02,Manager,68000.0
19,Zoya,23.0,F,Chennai,zoya@example.com,2024-08-21,Analyst,38000.0

In [30]:
df["Name"] = df["Name"].str.strip().str.title()

In [31]:
df

,Name,Age,Gender,City,Email,JoinDate,Category,Salary
0,Aayush,23.0,M,Del,aayush@example.com,2024-01-15,Analyst,28000.0
1,Riya,24.0,F,Delhi,riya.sharma@example.com,01/20/2024,Analyst,32000.0
2,Karan,NaN,M,Mum,karan@example.com,2024-02-03,Developer,45000.0
3,Neha,22.0,F,Mumbai,NaN,02/10/2024,Developer,42000.0
4,Aman,27.0,M,delhi,aman@example.com,2024-03-01,Analyst,NaN
5,Priya,24.0,F,Delhi,riya.sharma@example.com,2024-01-20,Analyst,32000.0
6,Vikram,31.0,M,Bengaluru,vikram@example.com,2024-03-15,Manager,60000.0
7,Sara,17.0,F,Mum,sara@example.com,NaN,Intern,15000.0
8,Rohan,29.0,M,Delhi NCR,rohan@example.com,2024-04-02,Developer,50000.0
9,Meera,26.0,F,Pune,meera@example.com,04/12/2024,Analyst,36000.0
10,Dev,35.0,M,Bengaluru,dev@example.com,2024-05-01,Manager,72000.0
11,Isha,21.0,F,Del,isha@example.com,2024-05-14,Intern,18000.0
12,Arjun,19.0,M,Pune,arjun@example.com,2024-06-01,Developer,39000.0
13,Karan,NaN,M,Mum,karan@example.com,2024-02-03,Developer,45000.0
14,Tara,16.0,F,Delhi,tara@example.com,2024-06-18,Intern,14000.0
15,Kabir,28.0,NaN,Chennai,kabir@example.com,2024-07-04,Analyst,41000.0
16,Anaya,25.0,F,Pune,anaya@example.com,2024-07-19,Developer,47000.0
17,Ishaan,30.0,M,Bengaluru,ishaan@example.com,2024-08-02,Manager,68000.0
18,Meera,26.0,F,Pune,meera@example.com,04/12/2024,Analyst,36000.0
19,Zoya,23.0,F,Chennai,zoya@example.com,2024-08-21,Analyst,38000.0

In [33]:
df["City"].str.contains("delhi", case = False)

0     False
1      True
2     False
3     False
4      True
5      True
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
Name: City, dtype: bool

In [34]:
df.head()

,Name,Age,Gender,City,Email,JoinDate,Category,Salary
0,Aayush,23.0,M,Del,aayush@example.com,2024-01-15,Analyst,28000.0
1,Riya,24.0,F,Delhi,riya.sharma@example.com,01/20/2024,Analyst,32000.0
2,Karan,NaN,M,Mum,karan@example.com,2024-02-03,Developer,45000.0
3,Neha,22.0,F,Mumbai,NaN,02/10/2024,Developer,42000.0
4,Aman,27.0,M,delhi,aman@example.com,2024-03-01,Analyst,NaN

In [35]:
df["Email"].str.split("@")

0          [aayush, example.com]
1     [riya.sharma, example.com]
2           [karan, example.com]
3                            NaN
4            [aman, example.com]
5     [riya.sharma, example.com]
6          [vikram, example.com]
7            [sara, example.com]
8           [rohan, example.com]
9           [meera, example.com]
10            [dev, example.com]
11           [isha, example.com]
12          [arjun, example.com]
13          [karan, example.com]
14           [tara, example.com]
15          [kabir, example.com]
16          [anaya, example.com]
17         [ishaan, example.com]
18          [meera, example.com]
19           [zoya, example.com]
Name: Email, dtype: object

In [39]:
df["JoinDate"] = pd.to_datetime(df["JoinDate"])

ValueError: time data "01/20/2024" doesn't match format "%Y-%m-%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [41]:
df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x >18 else "Minor")

In [42]:
df

,Name,Age,Gender,City,Email,JoinDate,Category,Salary,Age Group
0,Aayush,23.0,M,Del,aayush@example.com,2024-01-15,Analyst,28000.0,Adult
1,Riya,24.0,F,Delhi,riya.sharma@example.com,01/20/2024,Analyst,32000.0,Adult
2,Karan,NaN,M,Mum,karan@example.com,2024-02-03,Developer,45000.0,Minor
3,Neha,22.0,F,Mumbai,NaN,02/10/2024,Developer,42000.0,Adult
4,Aman,27.0,M,delhi,aman@example.com,2024-03-01,Analyst,NaN,Adult
5,Priya,24.0,F,Delhi,riya.sharma@example.com,2024-01-20,Analyst,32000.0,Adult
6,Vikram,31.0,M,Bengaluru,vikram@example.com,2024-03-15,Manager,60000.0,Adult
7,Sara,17.0,F,Mum,sara@example.com,NaN,Intern,15000.0,Minor
8,Rohan,29.0,M,Delhi NCR,rohan@example.com,2024-04-02,Developer,50000.0,Adult
9,Meera,26.0,F,Pune,meera@example.com,04/12/2024,Analyst,36000.0,Adult
10,Dev,35.0,M,Bengaluru,dev@example.com,2024-05-01,Manager,72000.0,Adult
11,Isha,21.0,F,Del,isha@example.com,2024-05-14,Intern,18000.0,Adult
12,Arjun,19.0,M,Pune,arjun@example.com,2024-06-01,Developer,39000.0,Adult
13,Karan,NaN,M,Mum,karan@example.com,2024-02-03,Developer,45000.0,Minor
14,Tara,16.0,F,Delhi,tara@example.com,2024-06-18,Intern,14000.0,Minor
15,Kabir,28.0,NaN,Chennai,kabir@example.com,2024-07-04,Analyst,41000.0,Adult
16,Anaya,25.0,F,Pune,anaya@example.com,2024-07-19,Developer,47000.0,Adult
17,Ishaan,30.0,M,Bengaluru,ishaan@example.com,2024-08-02,Manager,68000.0,Adult
18,Meera,26.0,F,Pune,meera@example.com,04/12/2024,Analyst,36000.0,Adult
19,Zoya,23.0,F,Chennai,zoya@example.com,2024-08-21,Analyst,38000.0,Adult

In [44]:
Gender = { "M":"Male", "F":"Female" }
df["Gender"] = df["Gender"].map(Gender)

In [45]:
df

,Name,Age,Gender,City,Email,JoinDate,Category,Salary,Age Group
0,Aayush,23.0,Male,Del,aayush@example.com,2024-01-15,Analyst,28000.0,Adult
1,Riya,24.0,Female,Delhi,riya.sharma@example.com,01/20/2024,Analyst,32000.0,Adult
2,Karan,NaN,Male,Mum,karan@example.com,2024-02-03,Developer,45000.0,Minor
3,Neha,22.0,Female,Mumbai,NaN,02/10/2024,Developer,42000.0,Adult
4,Aman,27.0,Male,delhi,aman@example.com,2024-03-01,Analyst,NaN,Adult
5,Priya,24.0,Female,Delhi,riya.sharma@example.com,2024-01-20,Analyst,32000.0,Adult
6,Vikram,31.0,Male,Bengaluru,vikram@example.com,2024-03-15,Manager,60000.0,Adult
7,Sara,17.0,Female,Mum,sara@example.com,NaN,Intern,15000.0,Minor
8,Rohan,29.0,Male,Delhi NCR,rohan@example.com,2024-04-02,Developer,50000.0,Adult
9,Meera,26.0,Female,Pune,meera@example.com,04/12/2024,Analyst,36000.0,Adult
10,Dev,35.0,Male,Bengaluru,dev@example.com,2024-05-01,Manager,72000.0,Adult
11,Isha,21.0,Female,Del,isha@example.com,2024-05-14,Intern,18000.0,Adult
12,Arjun,19.0,Male,Pune,arjun@example.com,2024-06-01,Developer,39000.0,Adult
13,Karan,NaN,Male,Mum,karan@example.com,2024-02-03,Developer,45000.0,Minor
14,Tara,16.0,Female,Delhi,tara@example.com,2024-06-18,Intern,14000.0,Minor
15,Kabir,28.0,NaN,Chennai,kabir@example.com,2024-07-04,Analyst,41000.0,Adult
16,Anaya,25.0,Female,Pune,anaya@example.com,2024-07-19,Developer,47000.0,Adult
17,Ishaan,30.0,Male,Bengaluru,ishaan@example.com,2024-08-02,Manager,68000.0,Adult
18,Meera,26.0,Female,Pune,meera@example.com,04/12/2024,Analyst,36000.0,Adult
19,Zoya,23.0,Female,Chennai,zoya@example.com,2024-08-21,Analyst,38000.0,Adult

In [46]:
df["City"].replace({"Del": "Delhi", "Mum":"Mumbai"})

0         Delhi
1         Delhi
2        Mumbai
3        Mumbai
4         delhi
5         Delhi
6     Bengaluru
7        Mumbai
8     Delhi NCR
9          Pune
10    Bengaluru
11        Delhi
12         Pune
13       Mumbai
14        Delhi
15      Chennai
16         Pune
17    Bengaluru
18         Pune
19      Chennai
Name: City, dtype: object

In [47]:
df["JoinDate"] = pd.to_datetime(
    df["JoinDate"], format="mixed", errors="coerce"
)

In [48]:
df

,Name,Age,Gender,City,Email,JoinDate,Category,Salary,Age Group
0,Aayush,23.0,Male,Del,aayush@example.com,2024-01-15,Analyst,28000.0,Adult
1,Riya,24.0,Female,Delhi,riya.sharma@example.com,2024-01-20,Analyst,32000.0,Adult
2,Karan,NaN,Male,Mum,karan@example.com,2024-02-03,Developer,45000.0,Minor
3,Neha,22.0,Female,Mumbai,NaN,2024-02-10,Developer,42000.0,Adult
4,Aman,27.0,Male,delhi,aman@example.com,2024-03-01,Analyst,NaN,Adult
5,Priya,24.0,Female,Delhi,riya.sharma@example.com,2024-01-20,Analyst,32000.0,Adult
6,Vikram,31.0,Male,Bengaluru,vikram@example.com,2024-03-15,Manager,60000.0,Adult
7,Sara,17.0,Female,Mum,sara@example.com,NaT,Intern,15000.0,Minor
8,Rohan,29.0,Male,Delhi NCR,rohan@example.com,2024-04-02,Developer,50000.0,Adult
9,Meera,26.0,Female,Pune,meera@example.com,2024-04-12,Analyst,36000.0,Adult
10,Dev,35.0,Male,Bengaluru,dev@example.com,2024-05-01,Manager,72000.0,Adult
11,Isha,21.0,Female,Del,isha@example.com,2024-05-14,Intern,18000.0,Adult
12,Arjun,19.0,Male,Pune,arjun@example.com,2024-06-01,Developer,39000.0,Adult
13,Karan,NaN,Male,Mum,karan@example.com,2024-02-03,Developer,45000.0,Minor
14,Tara,16.0,Female,Delhi,tara@example.com,2024-06-18,Intern,14000.0,Minor
15,Kabir,28.0,NaN,Chennai,kabir@example.com,2024-07-04,Analyst,41000.0,Adult
16,Anaya,25.0,Female,Pune,anaya@example.com,2024-07-19,Developer,47000.0,Adult
17,Ishaan,30.0,Male,Bengaluru,ishaan@example.com,2024-08-02,Manager,68000.0,Adult
18,Meera,26.0,Female,Pune,meera@example.com,2024-04-12,Analyst,36000.0,Adult
19,Zoya,23.0,Female,Chennai,zoya@example.com,2024-08-21,Analyst,38000.0,Adult